'use strict';

// セリフ
var Serif= [
	{
		serif: "今日は8月31日。",
		fukidash: null,
		chara: null,
		pos: null,
		exp: null,
	},
	{
		serif: null,
		fukidash: null,
		chara: "ganger",
		pos: "right",
		exp: "normal",
	},
	{
		serif: null,
		fukidash: null,
		chara: "renko",
		pos: "left",
		exp: "normal",
	},
	{
		serif: "約束を守りなさい。早く博霊神社に行かないと。",
		fukidash: "normal",
		chara: "ganger",
		pos: "right",
		exp: "normal",
	},
	{
		serif: "え、そんな約束してたっけ？",
		fukidash: "normal",
		chara: "renko",
		pos: "left",
		exp: "normal",
	},
	{
		serif: null,
		fukidash: null,
		chara: "merry",
		pos: "right",
		exp: "normal",
	},
	{
		serif: "どうしたの？",
		fukidash: "normal",
		chara: "merry",
		pos: "right",
		exp: "normal",
	},
	{
		serif: "実はかくかくしかじかで",
		fukidash: "normal",
		chara: "renko",
		pos: "left",
		exp: "normal",
	},
	{
		serif: "ふーん",
		fukidash: "normal",
		chara: "merry",
		pos: "right",
		exp: "normal",
	},
	{
		serif: "約束といえば、前に博霊神社の入り口を\n調べようって約束してたわね。",
		fukidash: "normal",
		chara: "renko",
		pos: "left",
		exp: "normal",
	},
	{
		serif: "そうだっけ？",
		fukidash: "normal",
		chara: "merry",
		pos: "right",
		exp: "normal",
	},
	{
		serif: "なんだか気になるわ。ねえ、今から行ってみない？",
		fukidash: "normal",
		chara: "renko",
		pos: "left",
		exp: "normal",
	},
	{
		serif: "今から！？面倒だわ…。",
		fukidash: "normal",
		chara: "merry",
		pos: "right",
		exp: "normal",
	},
	{
		serif: "そんな事言わずに行きましょうよ。",
		fukidash: "normal",
		chara: "renko",
		pos: "left",
		exp: "normal",
	},
	{
		serif: "うっ…急にめまいとフラつきと腹痛と頭痛が",
		fukidash: "normal",
		chara: "merry",
		pos: "right",
		exp: "normal",
	},
	{
		serif: "さっきまで元気だったじゃない！",
		fukidash: "normal",
		chara: "renko",
		pos: "left",
		exp: "normal",
	},
	{
		serif: "うーん、気が進まないわ。",
		fukidash: "normal",
		chara: "merry",
		pos: "right",
		exp: "normal",
	},
	{
		serif: "はぁ…。そんなに嫌なら仕方ないわね。\n私一人で行ってくるわ。",
		fukidash: "normal",
		chara: "renko",
		pos: "left",
		exp: "normal",
	},
];

module.exports = Serif;
