'use strict';

// セリフ
var Serif= [
	{
		serif: null,
		fukidashi: null,
		chara: "ganger",
		pos: "right",
		exp: "normal",
	},
	{
		serif: null,
		fukidashi: null,
		chara: "renko",
		pos: "left",
		exp: "normal",
	},
	{
		serif: "約束を守りなさい。\n早く博霊神社に行かないと。",
		fukidashi: "normal",
		chara: "ganger",
		pos: "right",
		exp: "normal",
	},
	{
		serif: "え、そんな約束してたっけ？",
		fukidashi: "normal",
		chara: "renko",
		pos: "left",
		exp: "normal",
	},
	{
		serif: null,
		fukidashi: null,
		chara: "merry",
		pos: "right",
		exp: "normal",
	},
	{
		serif: "どうしたの？",
		fukidashi: "normal",
		chara: "merry",
		pos: "right",
		exp: "normal",
	},
	{
		serif: "実はかくかくしかじかで",
		fukidashi: "normal",
		chara: "renko",
		pos: "left",
		exp: "normal",
	},
	{
		serif: "ふーん",
		fukidashi: "normal",
		chara: "merry",
		pos: "right",
		exp: "normal",
	},
	{
		serif: "約束といえば、前に博霊神社の\n入り口を調べようって\n約束してたわね。",
		fukidashi: "normal",
		chara: "renko",
		pos: "left",
		exp: "normal",
	},
	{
		serif: "そうだっけ？",
		fukidashi: "normal",
		chara: "merry",
		pos: "right",
		exp: "normal",
	},
	{
		serif: "なんだか気になるわ。\nねえ、今から行ってみない？",
		fukidashi: "normal",
		chara: "renko",
		pos: "left",
		exp: "normal",
	},
	{
		serif: "今から！？面倒だわ…。",
		fukidashi: "normal",
		chara: "merry",
		pos: "right",
		exp: "normal",
	},
	{
		serif: "そんな事言わずに\n行きましょうよ。",
		fukidashi: "normal",
		chara: "renko",
		pos: "left",
		exp: "normal",
	},
	{
		serif: "うっ…急にめまいと\nフラつきと腹痛と頭痛が",
		fukidashi: "normal",
		chara: "merry",
		pos: "right",
		exp: "normal",
	},
	{
		serif: "さっきまで\n元気だったじゃない！",
		fukidashi: "normal",
		chara: "renko",
		pos: "left",
		exp: "normal",
	},
	{
		serif: "うーん、気が進まないわ。",
		fukidashi: "normal",
		chara: "merry",
		pos: "right",
		exp: "normal",
	},
	{
		serif: "はぁ…。そんなに嫌なら\n仕方ないわね。\n私一人で行ってくるわ。",
		fukidashi: "normal",
		chara: "renko",
		pos: "left",
		exp: "normal",
	},
];

module.exports = Serif;
