'use strict';

var Constant = {
	DEBUG: true,

	LOADING_SCENE:  0,
	TITLE_SCENE:    1,
	PROLOGUE1_SCENE:2,
	PROLOGUE2_SCENE:3,
	STAGE_SCENE:    4,
	EPILOGUE_SCENE: 5,
	ENDING_SCENE:   6,

	BUTTON_LEFT:  0x01,
	BUTTON_UP:    0x02,
	BUTTON_RIGHT: 0x04,
	BUTTON_DOWN:  0x08,
	BUTTON_Z:     0x10,
	BUTTON_X:     0x20,
	BUTTON_SHIFT: 0x40,
	BUTTON_SPACE: 0x80,

	WAY_STATE:    0,
	TALK1_STATE:  1,
	BOSS_STATE:   2,
	TALK2_STATE:  3,
	RESULT_STATE: 4,
	GAMEOVER_STATE: 5,

	SPELLCARD_START_STATE: 0,
	SPELLCARD_EXEC_STATE:  1,

};

module.exports = Constant;
